#! python 3

import re

# Create a regex for phone numbers
phoneRegex = re.compile(r'''
# 0412 345 678, 0412345678, +61 412345678, +61412345678, +61 412 345 789

(
((\d)|(\+\d\d))     # area code
(\s)?               # first seperator (optional)
\d\d\d              # first three digits    
(\s)?               # second seperator (optional)
\d\d\d              # middle three digits
(\s)?               # third seperator (optional)
(\d\d\d)            # final three digits
)

''',re.VERBOSE)

# Create a regex for email addresses
emailRegex = re.compile(r'''
# some.+_thing@something.com

[a-zA-Z0-9_.+]+     # name part
@                   # @ symbol
[a-zA-Z0-9_.+]+     # domain name part

''', re.VERBOSE)


# Get the text
text = '0412 345 678, 0412345678, +61 412345678, +61412345678, +61 412 345 789, some.+_thing@something.com'

# Extract the email/phone from this text
extractedPhone = phoneRegex.findall(text)
extractedEmail = emailRegex.findall(text)

allPhoneNumbers = []
for phoneNumber in extractedPhone:
    allPhoneNumbers.append(phoneNumber[0])

print(allPhoneNumbers)
print(extractedEmail)
